insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Tucker 1948','Descrição Tucker 1948','http://www.livroandroid.com.br/livro/cars/classicos/Tucker.png','http://www.livroandroid.com.br/livro/cars/classicos/tucker.mp4','-23.564224','-46.653156','classicos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Chevrolet Corvette','Descrição Chevrolet Corvette','http://www.livroandroid.com.br/livro/cars/classicos/Chevrolet_Corvette.png','http://www.livroandroid.com.br/livro/cars/classicos/corvette.mp4','-23.564224','-46.653156','classicos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Chevrolet Impala Coupe','Descrição Chevrolet Impala Coupe','http://www.livroandroid.com.br/livro/cars/classicos/Chevrolet_Impala_Coupe.png','http://www.livroandroid.com.br/livro/cars/classicos/chevrolet_impala.mp4','-23.564224','-46.653156','classicos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Cadillac Deville Convertible','Descrição Cadillac Deville Convertible','http://www.livroandroid.com.br/livro/cars/classicos/Cadillac_Deville_Convertible.png','http://www.livroandroid.com.br/livro/cars/classicos/cadillac_deville.mp4','-23.564224','-46.653156','classicos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Chevrolet Bel-Air','Descrição Chevrolet Bel-Air','http://www.livroandroid.com.br/livro/cars/classicos/Chevrolet_BelAir.png','http://www.livroandroid.com.br/livro/cars/classicos/chevrolet_bel_air.mp4','-23.564224','-46.653156','classicos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Cadillac Eldorado','Descrição Cadillac Eldorado','http://www.livroandroid.com.br/livro/cars/classicos/Cadillac_Eldorado.png','http://www.livroandroid.com.br/livro/cars/classicos/cadillac_eldorado.mp4','-23.564224','-46.653156','classicos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Ferrari 250 GTO','Descrição Ferrari 250 GTO','http://www.livroandroid.com.br/livro/cars/classicos/Ferrari_250_GTO.png','http://www.livroandroid.com.br/livro/cars/classicos/ferrari_gto.mp4','-23.564224','-46.653156','classicos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Dodge Challenger','Descrição Dodge Challenger','http://www.livroandroid.com.br/livro/cars/classicos/Dodge_Challenger.png','http://www.livroandroid.com.br/livro/cars/classicos/dodge_challenger.mp4','','','classicos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Camaro SS 1969','Descrição Camaro SS 1969','http://www.livroandroid.com.br/livro/cars/classicos/Camaro_SS.png','http://www.livroandroid.com.br/livro/cars/classicos/camaro_ss.mp4','-23.564224','-46.653156','classicos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Ford Mustang 1976','Descrição Ford Mustang 1976','http://www.livroandroid.com.br/livro/cars/classicos/Ford_Mustang.png','http://www.livroandroid.com.br/livro/cars/classicos/ford_mustang.mp4','-23.564224','-46.653156','classicos');

insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Ferrari FF','Descrição Ferrari FF','http://www.livroandroid.com.br/livro/cars/esportivos/Ferrari_FF.png','http://www.livroandroid.com.br/livro/cars/esportivos/ferrari_ff.mp4','44.532218','10.864019','esportivos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('AUDI GT Spyder','Descrição AUDI GT Spyder','http://www.livroandroid.com.br/livro/cars/esportivos/Audi_Spyder.png','http://www.livroandroid.com.br/livro/cars/esportivos/audi_gt.mp4','-23.564224','-46.653156','esportivos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Porsche Panamera','Descrição Porsche Panamera','http://www.livroandroid.com.br/livro/cars/esportivos/Porsche_Panamera.png','http://www.livroandroid.com.br/livro/cars/esportivos/porsche_panamera.mp4','-23.564224','-46.653156','esportivos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Lamborghini Aventador','Descrição Lamborghini Aventador','http://www.livroandroid.com.br/livro/cars/esportivos/Lamborghini_Aventador.png','http://www.livroandroid.com.br/livro/cars/esportivos/lamborghini_aventador.mp4','-23.564224','-46.653156','esportivos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Chevrolet Corvette Z06','Descrição Chevrolet Corvette Z06','http://www.livroandroid.com.br/livro/cars/esportivos/Chevrolet_Corvette_Z06.png','http://www.livroandroid.com.br/livro/cars/esportivos/chevrolet_corvette.mp4','-23.564224','-46.653156','esportivos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('BMW M5','Descrição BMW M5','http://www.livroandroid.com.br/livro/cars/esportivos/BMW.png','http://www.livroandroid.com.br/livro/cars/esportivos/bmw-m5.mp4','-23.564224','-46.653156','esportivos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Renault Megane RS Trophy','Descrição Renault Megane RS Trophy','http://www.livroandroid.com.br/livro/cars/esportivos/Renault_Megane_Trophy.png','http://www.livroandroid.com.br/livro/cars/esportivos/renault_megane.mp4','-23.564224','-46.653156','esportivos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Maserati Grancabrio Sport','Descrição Maserati Grancabrio Sport','http://www.livroandroid.com.br/livro/cars/esportivos/Maserati_Grancabrio_Sport.png','http://www.livroandroid.com.br/livro/cars/esportivos/renault_megane.mp4','-23.564224','-46.653156','esportivos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('McLAREN MP4-12C','Descrição McLAREN MP4-12C','http://www.livroandroid.com.br/livro/cars/esportivos/McLAREN.png','http://www.livroandroid.com.br/livro/cars/esportivos/mcLaren.mp4','-23.564224','-46.653156','esportivos');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('MERCEDES-BENZ C63 AMG','Descrição MERCEDES-BENZ C63 AMG','http://www.livroandroid.com.br/livro/cars/esportivos/MERCEDES_BENZ_AMG.png','http://www.livroandroid.com.br/livro/cars/esportivos/mercedes.mp4','-23.564224','-46.653156','esportivos');

insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Bugatti Veyron','Descrição Bugatti Veyron','http://www.livroandroid.com.br/livro/cars/luxo/Bugatti_Veyron.png','http://www.livroandroid.com.br/livro/cars/luxo/bugatti_veyron.mp4','-23.564224','-46.653156','luxo');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Ferrari Enzo','Descrição Ferrari Enzo','http://www.livroandroid.com.br/livro/cars/luxo/Ferrari_Enzo.png','http://www.livroandroid.com.br/livro/cars/luxo/ferrari_enzo.mp4','-23.564224','-46.653156','luxo');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Lamborghini Reventon','Descrição Lamborghini Reventon','http://www.livroandroid.com.br/livro/cars/luxo/Lamborghini_Reventon.png','http://www.livroandroid.com.br/livro/cars/luxo/lamborghini _reventon.mp4','-23.564224','-46.653156','luxo');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Leblanc Mirabeau','Descrição Leblanc Mirabeau','http://www.livroandroid.com.br/livro/cars/luxo/Leblanc_Mirabeau.png','http://www.livroandroid.com.br/livro/cars/luxo/leblanc_mirabeau.mp4','-23.564224','-46.653156','luxo');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Shelby Supercars Ultimate','Descrição Shelby Supercars Ultimate','http://www.livroandroid.com.br/livro/cars/luxo/Shelby_Supercars_Ultimate.png','http://www.livroandroid.com.br/livro/cars/luxo/shelby.mp4','-23.564224','-46.653156','luxo');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Pagani Zonda','Descrição Pagani Zonda','http://www.livroandroid.com.br/livro/cars/luxo/Pagani_Zonda.png','http://www.livroandroid.com.br/livro/cars/luxo/pagani_zonda.mp4','-23.564224','-46.653156','luxo');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Koenigsegg CCX','Descrição Koenigsegg CCX','http://www.livroandroid.com.br/livro/cars/luxo/Koenigsegg_CCX.png','http://www.livroandroid.com.br/livro/cars/luxo/koenigsegg.mp4','-23.564224','-46.653156','luxo');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Mercedes SLR McLaren','Descrição Mercedes SLR McLaren','http://www.livroandroid.com.br/livro/cars/luxo/Mercedes_McLaren.png','http://www.livroandroid.com.br/livro/cars/luxo/mclaren_slr.mp4','-23.564224','-46.653156','luxo');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Rolls Royce Phantom','Descrição Rolls Royce Phantom','http://www.livroandroid.com.br/livro/cars/luxo/Rolls_Royce_Phantom.png','http://www.livroandroid.com.br/livro/cars/luxo/rolls_royce.mp4','-23.564224','-46.653156','luxo');
insert into car (name,description,url_picture,url_video,latitude,longitude,type) VALUES('Lexus LFA','Descrição Lexus LFA','http://www.livroandroid.com.br/livro/cars/luxo/Lexus_LFA.png','http://www.livroandroid.com.br/livro/cars/luxo/lexus.mp4','-23.564224','-46.653156','luxo');

INSERT INTO users(name, email, login, password) VALUES('User', 'user@gmail.com', 'user', '{bcrypt}$2a$10$U8C6CBGYtzCHisgo18KGZOcEtUf6XYlfN6Pbq9QdmQbNGPqS3YUQ2');
INSERT INTO users(name, email, login, password) VALUES('Admin', 'admin@gmail.com', 'admin', '{bcrypt}$2a$10$4R/wvJtSVifAsqEb82c4y.J9yBdCSSii5dkTja6L/nETX1ZORmGeC');

INSERT INTO role(name) VALUES('ROLE_USER');
INSERT INTO role(name) VALUES('ROLE_ADMIN');

INSERT INTO user_roles(user_id, role_id) VALUES(1, 1);
INSERT INTO user_roles(user_id, role_id) VALUES(2, 1);
INSERT INTO user_roles(user_id, role_id) VALUES(2, 2);
